- name: Upgrade nodes
  hosts: kubernetes
  become: true
  gather_facts: true
  serial: 1
  roles:
  - role: kubernetes-defaults
  - role: kubernetes-upgrade
  vars:
    version: "{{ kubernetes_version }}"
