# Pulled from upstream kubernetes:
# https://github.com/kubernetes/kubernetes/blob/850bfd9aa92423696dbb6de2070ab7494fdd99b1/cluster/gce/gci/configure-helper.sh#L1143

# My Modifications
# Added some healthcheck urls to exclude from audit logging.
# Added leases to the list of resources to exclude from audit logging.

apiVersion: audit.k8s.io/v1
kind: Policy
rules:
# The following requests were manually identified as high-volume and low-risk,
# so drop them.
- level: None
  users:
  - system:kube-proxy
  verbs:
  - watch
  resources:
  - group: ""
    resources:
    - endpoints
    - services
    - services/status
- level: None
  # Ingress controller reads `configmaps/ingress-uid` through the unsecured port.
  # TODO(#46983): Change this to the ingress controller service account.
  users:
  - system:unsecured
  namespaces:
  - kube-system
  verbs:
  - get
  resources:
  - group: ""
    resources:
    - configmaps
- level: None
  users:
  - kubelet
  verbs:
  - get
  resources:
  - group: ""
    resources:
    - nodes
    - nodes/status
- level: None
  userGroups:
  - system:nodes
  verbs:
  - get
  resources:
  - group: ""
    resources:
    - nodes
    - nodes/status
- level: None
  users:
  - system:kube-controller-manager
  - system:kube-scheduler
  - system:serviceaccount:kube-system:endpoint-controller
  verbs:
  - get
  - update
  namespaces:
  - kube-system
  resources:
  - group: ""
    resources:
    - endpoints
- level: None
  users:
  - system:apiserver
  verbs:
  - get
  resources:
  - group: ""
    resources:
    - namespaces
    - namespaces/status
    - namespaces/finalize
# Don't log HPA fetching metrics.
- level: None
  users:
  - system:kube-controller-manager
  verbs:
  - get
  - list
  resources:
  - group: "metrics.k8s.io"
# Don't log these read-only URLs.
- level: None
  nonResourceURLs:
  - /healthz*
  - /version
  - /swagger*
# Don't log events requests.
- level: None
  resources:
  - group: ""
    resources:
    - events

### My Additions
# Get rid of leases
- level: None
  resources:
  - group: coordination.k8s.io
    resources:
    - leases
# Get rid of health check endpoints
- level: None
  nonResourceURLs:
  - /healthz*
  - /version
  - /swagger*
  - /readyz*
  - /livez*
  - /api
### End My Additions


# Secrets, ConfigMaps, TokenRequest and TokenReviews can contain sensitive & binary data,
# so only log at the Metadata level.
- level: Metadata
  resources:
  - group: ""
    resources:
    - secrets
    - configmaps
    - serviceaccounts/token
  - group: authentication.k8s.io
    resources:
    - tokenreviews
  omitStages:
  - RequestReceived
# Get responses can be large; skip them.
- level: Request
  verbs:
  - get
  - list
  - watch
  resources:
  - group: ""
  - group: admissionregistration.k8s.io
  - group: apiextensions.k8s.io
  - group: apiregistration.k8s.io
  - group: apps
  - group: authentication.k8s.io
  - group: authorization.k8s.io
  - group: autoscaling
  - group: batch
  - group: certificates.k8s.io
  - group: extensions
  - group: metrics.k8s.io
  - group: networking.k8s.io
  - group: policy
  - group: rbac.authorization.k8s.io
  - group: settings.k8s.io
  - group: storage.k8s.io
  omitStages:
  - RequestReceived
# Default level for known APIs
- level: RequestResponse
  resources:
  - group: ""
  - group: admissionregistration.k8s.io
  - group: apiextensions.k8s.io
  - group: apiregistration.k8s.io
  - group: apps
  - group: authentication.k8s.io
  - group: authorization.k8s.io
  - group: autoscaling
  - group: batch
  - group: certificates.k8s.io
  - group: extensions
  - group: metrics.k8s.io
  - group: networking.k8s.io
  - group: policy
  - group: rbac.authorization.k8s.io
  - group: settings.k8s.io
  - group: storage.k8s.io
  omitStages:
  - RequestReceived
# Default level for all other requests.
- level: Metadata
  omitStages:
  - RequestReceived
