containerd_mirror: https://download.docker.com/linux/{{ ansible_distribution | lower }}
containerd_credentials: []

# containerd_credentials:
# - username: "username"
#   password: "password"
#   registry: "https://index.docker.io/v1/"
