- name: Check if we need to join the cluster
  ansible.builtin.shell:
    cmd: kubectl get nodes {{ inventory_hostname_short }} && exit 1 || exit 0
  register: kubernetes_needs_to_join_cluster_cmd
  failed_when: kubernetes_needs_to_join_cluster_cmd.rc != 0 and kubernetes_needs_to_join_cluster_cmd.rc != 1
  changed_when: false
  delegate_to: "{{ first_kube_control_plane }}"

- name: Set kubernetes_needs_to_join_cluster
  ansible.builtin.set_fact:
    kubernetes_needs_to_join_cluster: "{{ kubernetes_needs_to_join_cluster_cmd.rc == 0 }}"

- name: Set join token
  ansible.builtin.set_fact:
    join_token: "{{ hostvars[first_kube_control_plane].join_token }}"

- name: Create kubeadm file
  ansible.builtin.template:
    src: worker-kubeadm.yaml.j2
    dest: "{{ kubernetes_config_directory }}/kubeadm.yaml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: kubeadm_file
  when: kubernetes_needs_to_join_cluster

- name: Stop kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: stopped
    enabled: true
  when: kubernetes_needs_to_join_cluster

- name: Add the worker node
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      set -e
      kubeadm join --config {{ kubernetes_config_directory }}/kubeadm.yaml {{ kubeadm_init_extra_args | default('') }} 2>&1
    executable: /bin/bash
  changed_when: kubernetes_join_output.rc == 0
  register: kubeadm_join_output
  when: kubernetes_needs_to_join_cluster

# CIS 1.1.20
- name: CIS 1.1.20 - Secure certificates
  ansible.builtin.file:
    path: "{{ kubernetes_pki_directory }}"
    mode: '0600'
    recurse: true
  when: kubernetes_needs_to_join_cluster

# CIS 4.1.1
- name: CIS 4.1.1 - Set kubelet.service to 0600
  ansible.builtin.file:
    path: /usr/lib/systemd/system/kubelet.service
    mode: '0600'
  when: kubernetes_needs_to_join_cluster

# CIS 4.1.9
# STIG V-242407
- name: CIS 4.1.9, STIG V-242407 - Set kubelet config.yaml to 0600
  ansible.builtin.file:
    path: /var/lib/kubelet/config.yaml
    mode: '0600'
  when: kubernetes_needs_to_join_cluster

# STIG V-242397
- name: Secure static pod path
  ansible.builtin.replace:
    regexp: 'staticPodPath:.*'
    replace: 'staticPodPath:'
    path: /var/lib/kubelet/config.yaml
  when: kubernetes_needs_to_join_cluster

- name: Retart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true
  when: kubernetes_needs_to_join_cluster

- name: Post security hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_security }}"
  when: kubernetes_hookfiles.post_security is defined

- name: Post worker node join hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_worker_join }}"
  when: kubernetes_hookfiles.post_worker_join is defined

- name: Approve all CSR's for kubelet's
  ansible.builtin.shell:
    cmd: |
      # don't do a set -e here because we want to continue if there are no pending CSRs
      set -o pipefail
      kubectl --namespace kube-system --kubeconfig /etc/kubernetes/admin.conf get csr | grep Pending | awk '{print $1}' | xargs kubectl --namespace kube-system --kubeconfig /etc/kubernetes/admin.conf certificate approve
      exit 0
    executable: /bin/bash
  delegate_to: "{{ first_kube_control_plane }}"
  changed_when: true
