- name: Set fact first_kube_control_plane
  ansible.builtin.set_fact:
    first_kube_control_plane: "{{ groups['control_planes'] | first }}"
  run_once: true
  when: first_kube_control_plane is not defined
