- name: Create new encryption key
  register: encryption_key_temp
  ansible.builtin.shell:
    cmd: |
      [ ! -f {{ kubernetes_config_directory }}/secretbox-encryptionkey ] && openssl rand -base64 32 > "{{ kubernetes_config_directory }}/secretbox-encryptionkey"
      cat {{ kubernetes_config_directory }}/secretbox-encryptionkey
      chmod 0600 {{ kubernetes_config_directory }}/secretbox-encryptionkey
  delegate_to: "{{ first_kube_control_plane }}"
  run_once: true
  when: not encryption_key is defined
  changed_when: true

- name: Set encryption key fact
  ansible.builtin.set_fact:
    encryption_key: "{{ encryption_key_temp.stdout }}"
  delegate_to: "{{ first_kube_control_plane }}"
  run_once: true
