- name: Install CNI
  block:

  - name: Install Calico
    ansible.builtin.shell:
      cmd: |
        set -e
        set -o pipefail
        kubectl apply --kubeconfig /etc/kubernetes/admin.conf -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/calico.yaml \
          | tee /etc/kubernetes/output/calico-installed
      creates: /etc/kubernetes/output/calico-installed
      executable: /bin/bash
    register: calico
    when: kubernetes_cni_calico

  rescue:
  - name: Delete calico-installed
    ansible.builtin.file:
      path: /etc/kubernetes/output/calico-installed
      state: absent

  - name: Write calico to stdout
    ansible.builtin.debug:
      msg: |
        {{ calico.stdout_lines }}
        {{ calico.stderr_lines }}
    when: kubernetes_cni_calico and calico.stdout_lines is defined

  - name: Fail calico
    ansible.builtin.fail:
      msg: "Failed to install Calico"
