- name: Kubernetes - Download GPG keyring
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}
    mode: '0644'
    owner: root
    group: root

- name: Add an apt signing key for Kubernetes
  ansible.builtin.shell: gpg --batch --yes --dearmor /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}
  args:
    creates: /etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-{{ kubernetes_version }}.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
    state: present
    filename: kubernetes-{{ kubernetes_version }}.list

- name: Get latest specified version of kubeadm, kubelet and kubectl
  ansible.builtin.shell: apt-cache madison kubeadm | grep "{{ kubernetes_version }}" | head -n 1 | awk '{print $3}'
  register: k8s_version_temp

- name: Set k8s_version fact
  ansible.builtin.set_fact:
    k8s_version: "{{ k8s_version_temp.stdout }}"

- name: Install kubeadm, kubelet and kubectl
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - kubeadm={{ k8s_version }}
    - kubelet={{ k8s_version }}
    - kubectl={{ k8s_version }}

- name: Hold kubeadm, kubelet and kubectl
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
  - kubeadm
  - kubelet
  - kubectl

- name: Start kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
