- name: Pre-prequisites hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.pre_prerequisites }}"
  when: kubernetes_hookfiles.pre_prerequisites is defined

- name: Install Packages
  ansible.builtin.import_tasks: install-packages.yml

- name: Post install packages hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_install_packages }}"
  when: kubernetes_hookfiles.post_install_packages is defined

- name: Make sure kubernetes config directory exists
  ansible.builtin.file:
    path: "{{ kubernetes_config_directory }}"
    state: directory
    mode: '0700'

- name: Make sure /etc/kubernetes/output directory exists
  ansible.builtin.file:
    path: /etc/kubernetes/output
    state: directory
    mode: '0700'

- name: Configure ContainerD
  ansible.builtin.import_tasks: configure-containerd.yml

- name: Configure Kernel
  ansible.builtin.import_tasks: configure-kernel.yml

- name: Configure Swap
  ansible.builtin.import_tasks: configure-swap.yml
  when: allowswap is not defined

- name: Pull kubernetes images
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      kubeadm config images pull | tee /etc/kubernetes/images-pulled-{{ kubernetes_version }}
    creates: /etc/kubernetes/images-pulled-{{ kubernetes_version }}
    executable: /bin/bash
  register: kubeadm_images_pulled

- name: Write kubeadm images pulled to stdout
  ansible.builtin.debug:
    msg: "{{ kubeadm_images_pulled.stdout_lines }}"

- name: Define first_kube_control_plane
  ansible.builtin.import_tasks: define-first-kube-control.yml

- name: Generate the encryption key
  ansible.builtin.import_tasks: define-encryption-key.yml

- name: Configure control planes
  ansible.builtin.import_tasks: configure-control-plane.yml
  when: inventory_hostname in groups['control_planes']

- name: Configure control plane hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_configure_control_planes }}"
  when:
  - inventory_hostname in groups['control_planes']
  - kubernetes_hookfiles.post_configure_control_planes is defined

- name: Configure worker hooks
  ansible.builtin.include_tasks: "{{ item }}"
  with_items: "{{ kubernetes_hookfiles.post_configure_workers }}"
  when:
  - inventory_hostname in groups['worker_nodes']
  - kubernetes_hookfiles.post_configure_workers is defined
