- name: Create kubeadm file
  ansible.builtin.template:
    src: secondary-control-plane-kubeadm.yaml.j2
    dest: "{{ kubernetes_config_directory }}/kubeadm.yaml"
    owner: root
    group: root
    mode: '0600'
    backup: true
  register: kubeadm_file

- name: Pull control plane certs down
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      kubeadm join phase control-plane-prepare download-certs --config {{ kubernetes_config_directory }}/kubeadm.yaml -v5 2>&1 | tee /etc/kubernetes/output/kubeadm-certs
    executable: /bin/bash
    creates: "{{ kubernetes_pki_directory }}/ca.crt"

- name: Stop kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: stopped
    enabled: true

- name: Add the control plane node
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      kubeadm join --config {{ kubernetes_config_directory }}/kubeadm.yaml {{ kubeadm_init_extra_args | default('') }} 2>&1 | tee /etc/kubernetes/output/kubeadm-join
    creates: /etc/kubernetes/output/kubeadm-join
    executable: /bin/bash
  register: kubeadm_init_output

- name: Start kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true

# CIS 1.1.20
- name: CIS 1.1.20 - Secure certificates
  ansible.builtin.shell:
    cmd: chmod 0600 --recursive {{ kubernetes_pki_directory }}/*.crt
  changed_when: true

# CIS 4.1.1
- name: CIS 4.1.1 - Set kubelet.service to 0600
  ansible.builtin.file:
    path: /usr/lib/systemd/system/kubelet.service
    mode: '0600'

# CIS 4.1.9
# STIG V-242407
- name: CIS 4.1.9, STIG V-242407 - Set kubelet config.yaml to 0600
  ansible.builtin.file:
    path: /var/lib/kubelet/config.yaml
    mode: '0600'
