# Required
# This is the IP address of the Kubernetes control plane. This is the IP address that the proxies will bind to.
kubernetes_control_plane_ip: null

kubernetes_containerd_credentials: []
# kubernetes_containerd_credentials:
# - username: "username"
#   password: "password"
#   registry: "docker.io"
kubernetes_containerd_mirror: https://download.docker.com/linux/{{ ansible_distribution | lower }}

# CIS 1.1.12
kubernetes_etcd_init_container_image: alpine:latest
kubernetes_etcd_group_id: 500
kubernetes_etcd_user_id: 500

kubernetes_admission_control_plugins:
# CIS 1.2.11
- AlwaysPullImages

# CIS 1.2.14
- NodeRestriction

# Defaults as of 1.31
- CertificateApproval
- CertificateSigning
- CertificateSubjectRestriction
- DefaultIngressClass
- DefaultStorageClass
- DefaultTolerationSeconds
- LimitRanger
- MutatingAdmissionWebhook
- NamespaceLifecycle
- PersistentVolumeClaimResize
- PodSecurity
- Priority
- ResourceQuota
- RuntimeClass
- ServiceAccount
- StorageObjectInUseProtection
- TaintNodesByCondition
- ValidatingAdmissionPolicy
- ValidatingAdmissionWebhook
kubernetes_admission_configuration:
  audit: "baseline"
  audit_version: "latest"
  enforce: "privileged"
  enforce_version: "latest"
  exemptions:
    usernames:
    - admin
    namespaces:
    - kube-system
  warn: "privileged"
  warn_version: "latest"

# Required to be set, this is the FQDN of the load balanced API endpoint.
# Your clients will use this endpoint to interface with the cluster.
# This DNS entry should already be setup before running the playbooks.
kubernetes_api_endpoint: null

kubernetes_api_port: 6443

# Expects an array of dictionaries with the following keys: name, source, destination, mode
# mode defaults to File
# destination defaults to the same value as source
# name must be unique and not any of the following
# - authentication
# - authorization
# - encryption-config
# - audit-policy
# - audit-log
# - admission-configuration
# - ca-certs
# - etc-ca-certificates
# - k8s-certs
# - usr-local-share-ca-certificates
# - usr-share-ca-certificates
kubernetes_api_server_additional_mounts: []

# Extra arguments to pass to the Kubernetes API Server
# Must not contain any of the following names:
# audit-log-path
# audit-log-maxage
# audit-log-maxbackup
# audit-log-maxsize
# tls-cipher-suites
# audit-policy-file
# authentication-config
# authorization-config
# enable-admission-plugins
# encryption-provider-config
# encryption-provider-config-automatic-reload
# kubelet-certificate-authority
# profiling
# admission-control-config-file
# tls-min-version
# service-account-issuer

# Example:
# kubernetes_api_server_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_api_server_extra_args: []

kubernetes_audit_log_max_age: 30
kubernetes_audit_log_max_backup: 10
kubernetes_audit_log_max_size: 100
kubernetes_audit_log_path: /var/log/apiserver/audit.log
kubernetes_authorization_pre_node: []
kubernetes_authorization_pre_rbac: []
kubernetes_authorization_post_rbac: []

# If set, it must be external
kubernetes_cloud_provider: null

kubernetes_config_directory: /etc/kubernetes/config
kubernetes_control_plane_additional_files: []
kubernetes_control_plane_additional_templates: []
kubernetes_control_plane_check_interval: 100ms

# Extra arguments to pass to the Kubernetes Controller Manager
# Must not contain any of the following names:
# authentication-tolerate-lookup-failure
# node-cidr-mask-size
# terminated-pod-gc-threshold
# cluster-signing-duration
# profiling
# tls-min-version

# Example:
# kubernetes_controller_manager_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_controller_manager_extra_args: []

kubernetes_cluster_signing_duration: 8760h
kubernetes_cluster_name: cluster
kubernetes_dns_domain: cluster.local

# Required
# 32 bytes used to encrypt the etcd data, this should be base64 encoded.
kubernetes_encryption_key: null

# Extra arguments to pass to the ETCD backend
# Must not contain any of the following names:
# authentication-tolerate-lookup-failure
# peer-auto-tls
# auto-tls

# Example:
# kubernetes_etcd_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_etcd_extra_args: []

# in order of execution
kubernetes_hookfiles:
  # run before any tasks that configure the proxies
  pre_proxies: []

  # run after the tasks that configure the proxies
  post_proxies: []

  # At the beginning of every major section run these, this is a good spot to put in default variables
  default_configuration: []

  # At the beginning of installing pre-requisites.
  pre_prerequisites: []

  # After installing packages
  post_install_packages: []

  # After configuring the control planes with the required configuration files
  post_configure_control_planes: []

  # After configuring the workers with the required configuration files
  post_configure_workers: []

  # After the cluster has been initialized and before anything has been added or configured in the cluster.
  # Host level security policies that are deferred to after the cluster creation are not applied yet.
  # This is where you want to install your CNI, see the `example-hooks/post_cluster_init` directory for examples.
  post_cluster_init: []

  # Executes after the node has been joined to the cluster and after security policies have applied.
  post_security: []

  # after the additional control plane has been joined to the cluster
  post_control_plane_join: []

  # after all control planes have been joined to the cluster
  post_control_planes: []

  # after the worker node has been joined to the cluster
  post_worker_join: []

  # after all worker nodes have been joined to the cluster
  post_workers: []

kubernetes_init_skip_phases: []

# Install Helm on the control plane nodes
kubernetes_install_helm: true

# Install Kustomize on the control plane nodes
kubernetes_install_kustomize: true

kubernetes_kubeadm_init_extra_args: ""

kubernetes_mirror: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/
kubernetes_node_cidr_mask_size: 24

kubernetes_output_directory: /etc/kubernetes/output

kubernetes_pki_directory: /etc/kubernetes/pki
kubernetes_pod_subnet: 10.244.0.0/16
kubernetes_podpidslimit: 1000
# CIS 1.2.15, 1.3.2, 1.4.1 - Profiling should be turned off. Default in kubeadm is true.
# STIG V-242409
kubernetes_profiling: false

kubernetes_proxy_haproxy_config_file: haproxy.cfg.j2
kubernetes_proxy_keepalived_config_file: keepalived.conf.j2

# Extra arguments to pass to the Kubernetes Scheduler
# Must not contain any of the following names:
# authentication-tolerate-lookup-failure
# profiling
# tls-min-version

# Example:
# kubernetes_scheduler_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_scheduler_extra_args: []

kubernetes_scripts_directory: /opt/kubernetes/scripts
kubernetes_service_subnet: 10.96.0.0/16
kubernetes_streamingconnectionidletimeout: 5m
kubernetes_terminated_pod_gc_threshold: 10

# Required
# This is the issuer URL of the OIDC provider. Do not include the .well-known/openid-configuration path.
kubernetes_oidc_issuer_url: null
# Required
# This is the client ID of the OIDC provider.
kubernetes_oidc_client_id: null

kubernetes_oidc_username_claim: upn
kubernetes_oidc_username_prefix: "oidc:"
kubernetes_oidc_group_claim: roles
kubernetes_oidc_group_prefix: "oidc:"
kubernetes_oidc_uid_claim: oid

# You can override the default, https://kubernetes.default.svc.cluster.local, with any url.
kubernetes_service_account_issuer: null

# CIS 4.2.12
# STIG V-242418
kubernetes_strong_cypher_suites:
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

kubernetes_version: "1.31"
skip_checks: false

# Required
# This is the password used by keepalived in the proxy nodes to move the floating ip between proxy nodes
vrrp_password: null

# Required
# The floating Kubernetes control plane IP address will live on this interface
vrrp_interface: null

# Required
# The virtual router id for the Kubernetes control plane keepalived instance
vrrp_virtual_router_id: null
