kubernetes_cilium_clusterpoolipv4podcidrlist:
- 10.2.128.0/17

# CIS 1.1.12
kubernetes_etcd_init_container_image: alpine:latest
kubernetes_etcd_group_id: 500
kubernetes_etcd_user_id: 500

kubernetes_kubelet_csr_approver_bypass_dns_checks: false
kubernetes_kubelet_csr_approver_ips: null
kubernetes_kubelet_csr_approver_regex: null

kubernetes_admission_control_plugins:
# CIS 1.2.11
- AlwaysPullImages

# CIS 1.2.14
- NodeRestriction

# Defaults as of 1.31
- CertificateApproval
- CertificateSigning
- CertificateSubjectRestriction
- DefaultIngressClass
- DefaultStorageClass
- DefaultTolerationSeconds
- LimitRanger
- MutatingAdmissionWebhook
- NamespaceLifecycle
- PersistentVolumeClaimResize
- PodSecurity
- Priority
- ResourceQuota
- RuntimeClass
- ServiceAccount
- StorageObjectInUseProtection
- TaintNodesByCondition
- ValidatingAdmissionPolicy
- ValidatingAdmissionWebhook
kubernetes_admission_configuration:
  audit: "baseline"
  audit_version: "latest"
  enforce: "privileged"
  enforce_version: "latest"
  exemptions:
    usernames:
    - admin
    namespaces:
    - kube-system
  warn: "privileged"
  warn_version: "latest"
kubernetes_api_endpoint: null
kubernetes_api_port: 6443
kubernetes_audit_log_max_age: 30
kubernetes_audit_log_max_backup: 10
kubernetes_audit_log_max_size: 100
kubernetes_audit_log_path: /var/log/apiserver/audit.log
kubernetes_config_directory: /etc/kubernetes/config
kubernetes_cluster_signing_duration: 8760h
kubernetes_cluster_name: cluster
kubernetes_dns_domain: cluster.local

# 32 bytes used to encrypt the etcd data, this should be base64 encoded.
# if not specified, a random key will be generated and stored on the first control plane node.
kubernetes_encryption_key: null

# in order of execution
kubernetes_hookfiles:
  # At the beginning of every major section run these, this is a good spot to put in default variables
  default_configuration: []

  # At the beginning of installing pre-requisites.
  pre_prerequisites: []

  # After installing packages
  post_install_packages: []

  # After configuring the control planes with the required configuration files
  post_configure_control_planes: []

  # After configuring the workers with the required configuration files
  post_configure_workers: []

  # After the cluster has been initialized and before anything has been added or configured in the cluster.
  # Host level security policies that are deferred to after the cluster creation are not applied yet.
  # This is where you want to install your CNI, see the `example-hooks/post_cluster_init` directory for examples.
  post_cluster_init: []

  # Executes after the node has been joined to the cluster and after security policies have applied.
  post_security: []

  # after the additional control plane has been joined to the cluster
  post_control_plane_join: []

  # after all control planes have been joined to the cluster
  post_control_planes: []

  # after the worker node has been joined to the cluster
  post_worker_join: []

  # after all worker nodes have been joined to the cluster
  post_workers: []

kubernetes_init_skip_phases: []
kubernetes_kubeadm_init_extra_args: ""

# azure or int128
kubernetes_kubelogin_flavor: azure
kubernetes_kubelogin_azure_tenant: null
kubernetes_kubelogin_azure_client_id: "{{ kubernetes_oidc_client_id }}"
kubernetes_kubelogin_int128_use_pkce: false

kubernetes_mirror: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/
kubernetes_node_cidr_mask_size: 24
kubernetes_pki_directory: /etc/kubernetes/pki
kubernetes_pod_subnet: 10.244.0.0/16
kubernetes_podpidslimit: 100
# CIS 1.2.15, 1.3.2, 1.4.1 - Profiling should be turned off. Default in kubeadm is true.
# STIG V-242409
kubernetes_profiling: false

kubernetes_scripts_directory: /opt/kubernetes/scripts
kubernetes_service_subnet: 10.96.0.0/16
kubernetes_streamingconnectionidletimeout: 5m
kubernetes_terminated_pod_gc_threshold: 10

kubernetes_oidc_issuer_url: null
kubernetes_oidc_client_id: null
kubernetes_oidc_username_claim: upn
kubernetes_oidc_username_prefix: "oidc:"
kubernetes_oidc_group_claim: roles
kubernetes_oidc_group_prefix: "oidc:"
kubernetes_oidc_uid_claim: oid

# You can override the default, https://kubernetes.default.svc.cluster.local, with any url.
kubernetes_service_account_issuer: null

# CIS 4.2.12
# STIG V-242418
kubernetes_strong_cypher_suites:
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

kubernetes_version: "1.31"

kubernetes_vsphere_server: null
kubernetes_vsphere_username: null
kubernetes_vsphere_password: null
kubernetes_vsphere_datacenter: null
