- name: "Update apt repositories"
  ansible.builtin.apt:
    update_cache: yes

- name: Docker - Install Docker
  ansible.builtin.apt:
    name:
    - gpg
    state: present
    
- name: Docker - Create keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Docker - Download GPG keyring
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker
    mode: '0644'
    owner: root
    group: root

- name: Docker - Dearmor gpg keyring
  ansible.builtin.shell: gpg --batch --yes --dearmor /etc/apt/keyrings/docker
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Docker - Add Docker Repository - Official
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} jammy stable
    state: present
    update_cache: yes
    filename: docker

- name: Install Container-d
  ansible.builtin.apt:
    name:
    - containerd.io
    state: present
  when: containerd_only is defined

- name: Docker - Install Docker
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present
  when: containerd_only is not defined

- name: Add edward to Docker group
  ansible.builtin.user:
    name: edward
    groups: docker
    append: yes
  when: containerd_only is not defined

