- name: Configure the proxies
  hosts: proxies
  become: true
  tasks:
  roles:
  - role: kubernetes-proxy

- name: "Install containerd.io"
  hosts:
  - kubernetes
  become: true
  roles:
  - role: docker
    vars:
      containerd_only: true

- name: "Install kubernetes"
  hosts:
  - kubernetes
  serial: 1
  become: true
  roles:
  - role: kubernetes
